kind: ReplicationController
apiVersion: v1
metadata:
  name: spark-jupyter2
spec:
  replicas: 1
  selector:
    component: spark-jupyter2
  template:
    metadata:
      labels:
        component: spark-jupyter2
    spec:
      containers:
        - name: spark-jupyter2
          image: dpavlov/spark:latest
          args: ["/usr/share/jupyter.sh"]
          ports:
            - containerPort: 9999
          resources:
            requests:
              cpu: 100m
