kind: ReplicationController
apiVersion: v1
metadata:
  name: spark-master
spec:
  replicas: 1
  selector:
    component: spark-master
  template:
    metadata:
      labels:
        component: spark-master
    spec:
      containers:
        - name: spark-master
          image: dpavlov/spark:latest
          args: ["/usr/share/master.sh"]
          ports:
            - containerPort: 7077
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
