kind: ReplicationController
apiVersion: v1
metadata:
  name: spark-slave
spec:
  replicas: 3
  selector:
    component: spark-slave
  template:
    metadata:
      labels:
        component: spark-slave
    spec:
      containers:
        - name: spark-slave
          image: dpavlov/spark:2.0
          args: ["/bin/bash","-c","cd /usr/local/spark; bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077 --webui-port 8081; tail -F /usr/local/spark/logs/*"]
          ports:
            - containerPort: 7077
            - containerPort: 8080
            - containerPort: 4040
            - containerPort: 8081
          resources:
            requests:
              cpu: 100m
